### ISSUE TITLE
BF: address search is broken for Burkina Faso

### ISSUE THREAD

**Issue by mhl** [mysociety/yournextrepresentative#575]
e.g. the test case I always use ('Ouagadougou') is causing a 500 error:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/data/vhost/candidats.data.gov.bf/yournextrepresentative/candidates/views/frontpage.py", line 23, in dispatch
    return super(AddressFinderView, self).dispatch(*args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/views/generic/edit.py", line 214, in post
    if form.is_valid():
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/forms/forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/forms/forms.py", line 392, in full_clean
    self._clean_fields()
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/forms/forms.py", line 410, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/data/vhost/candidats.data.gov.bf/yournextrepresentative/candidates/forms.py", line 32, in clean_address
    check_address(address, self.country)
  File "/data/vhost/candidats.data.gov.bf/yournextrepresentative/candidates/models/address.py", line 30, in check_address
    mapit_lookup_url += '?type=' + ','.join(settings.MAPIT_TYPES)
  File "/data/vhost/candidats.data.gov.bf/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'MAPIT_TYPES'
```

**Comment by mhl** [comment]
Fixed with 2868c1a65
